### ISSUE TITLE
Bug: data shows error

### ISSUE THREAD

**Issue by Alexzhuangyao** [blocksecteam/Phalcon#1]
### Transaction Hash

0x933d19d7d822e84e34ca47ac733226367fbee0d9c0c89d88d431c4f99629d77a

### Chain

Binance Smart Chain

### What did you expect to happen?

https://phalcon.blocksec.com/tx/bsc/0x933d19d7d822e84e34ca47ac733226367fbee0d9c0c89d88d431c4f99629d77a

the amount of [7] step should be 111.622391174831097929  but it shows [7]1,111.622391174831097928 USDC

### What actually happened?

https://phalcon.blocksec.com/tx/bsc/0x933d19d7d822e84e34ca47ac733226367fbee0d9c0c89d88d431c4f99629d77a

the amount of [7] step should be 111.622391174831097929  but it shows [7]1,111.622391174831097928 USDC

**Comment by yajin** [comment]
Thanks, the issue has been fixed in the online version.
