### ISSUE TITLE
Bug: `net_version` call returns 0 on a forked network

### ISSUE THREAD

**Issue by shahnami** [blocksecteam/Phalcon#13]
### Transaction Hash

n/a

### Chain

Ethereum

### What did you expect to happen?

Expected to return the `chain_id` (9991)

### What actually happened?

Returned `0`

### Additional comments

I don't recall this happening before. Is this expected behaviour, or has this changed recently?

**Comment by txlirui** [comment]
Thanks for the feedback. The issue has been fixed.

**Comment by shahnami** [comment]
Confirmed, thanks for the quick response!
