### ISSUE TITLE
Bug: (fill in)

### ISSUE THREAD

**Issue by Beosin20180329** [blocksecteam/Phalcon#4]
### Transaction Hash

0xc09678fec49c643a30fc8e4dec36d0507dae7e9123c270e1f073d335deab6cf0

### Chain

Binance Smart Chain

### What did you expect to happen?

![image](https://user-images.githubusercontent.com/58016160/220544901-878eeead-1d42-4797-8808-3efa6936b52f.png)

### What actually happened?

![image](https://user-images.githubusercontent.com/58016160/220544909-49ebdbb3-ca8c-4ee7-800c-39302091d6f0.png)

**Comment by yajin** [comment]
it works now. Thanks for your feedback.
