### ISSUE TITLE
Bug: (fill in)

### ISSUE THREAD

**Issue by rwk2095** [blocksecteam/Phalcon#5]
### Transaction Hash

0xd48758ef48d113b78a09f7b8c7cd663ad79e9965852e872fdfc92234c3e598d2

### Chain

Binance Smart Chain

### What did you expect to happen?

data returned

### What actually happened?

"Sorry, we are unable to locate this transaction."

### Additional comments

I am not getting any results on BSC. Other chains seem to be okay.

**Comment by yajin** [comment]
It works now. Thanks for your report.
