### ISSUE TITLE
Bug: Differing info from bscscan

### ISSUE THREAD

**Issue by brianleect** [blocksecteam/Phalcon#6]
### Transaction Hash

0xcb20e3fe7c978d2fc16ffb4645e4227e888eef1ed7612072ca2cb0a93615c94d

### Chain

Bsc

### What did you expect to happen?

Match bscscan info.

https://bscscan.com/tx/0xcb20e3fe7c978d2fc16ffb4645e4227e888eef1ed7612072ca2cb0a93615c94d

### What actually happened?

Very different output shown. Input data matched but gas consumed and execution was very different.

### Additional comments

Perhaps a reorg occurred messing up expected state?

**Comment by blocksecaudit** [comment]
looks the information is consistent now.

**Comment by yajin** [comment]
looks like the information is consistent now.

**Comment by brianleect** [comment]
Closing as it seems resolved.
